SRC = Server.cpp Joueur.cpp Action.cpp Plateau.cpp Pierre.cpp
OBJ = $(SRC:%.cpp=%.o)
NAME = Server
CXX = g++ -pthread -Wall -Wextra -Wpedantic -Werror -std=c++14
RM = rm -f
all: $(NAME)
$(NAME):	$(OBJ)
		$(CXX)	$(OBJ) -o $(NAME)
		
clean:
	$(RM)	$(OBJ)
fclean:	clean
	$(RM)	$(NAME)
	
re:	fclean all
.PHONY: all clean flean re

